name: Deploy Repository via rsync

on:
  workflow_dispatch:
    inputs:
      deployment_dest:
        description: 'Target server directory, leave blank for root directory'
        required: false
        default: ''
      post_deploy_commands:
        description: 'Post deployment command'
        required: false
        default: ''
      cleanup_deleted_files:
        description: 'Cleanup deleted files?'
        type: choice
        required: false
        default: "yes"
        options:
          - "yes"
          - "no"
      enable_health_check:
        description: 'Enable wordpress health check?'
        type: choice
        required: false
        default: "yes"
        options:
          - "yes"
          - "no"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy files
        uses: narethiya-godaddy/git-deploy-poc@v0.0.1
        with:
          remote_host: ${{ secrets.SSH_REMOTE }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          deployment_dest: ${{ github.event.inputs.deployment_dest }}
          post_deploy_commands: ${{ github.event.inputs.post_deploy_commands }}
          cleanup_deleted_files: ${{ github.event.inputs.cleanup_deleted_files }}
          enable_health_check: ${{ github.event.inputs.enable_health_check }}
