name: Deploy Repository via rsync

on:
  workflow_dispatch:
    inputs:
      deployment_dest:
        description: 'Target server directory, leave blank for root directory'
        required: false
        default: '.'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy files
        uses: godaddy-wordpress/git-deploy-poc@v0.0.1
        with:
          remote_host: "cj2.bd6.myftpupload.com"
          ssh_user: "git_deployer_5e2d15a41f_64413"
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          deployment_dest: ${{ github.event.inputs.deployment_dest }}
