name: Deploy Repository via rsync

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: "SSH username"
        required: true
        default: '28985_deployer'
      remote_host:
        description: "Remote host"
        required: true
        default: 'j0x.605.myftpupload.com'
      deployment_dest:
        description: 'Server dir to deploy instead of the entire repo'
        required: false
        default: '.'
      post_deploy_commands:
        description: 'Post deployment command'
        required: false
        default: ''
      cleanup_deleted_files:
        description: 'Cleanup deleted files?'
        required: false
        default: "yes"
        options:
          - "yes"
          - "no"
      enable_health_check:
        description: 'Enable wordpress health check?'
        required: false
        default: "yes"
        options:
          - "yes"
          - "no"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy files
        uses: narethiya-godaddy/git-deploy-poc@v0.0.1
        with:
          remote_host: ${{ github.event.inputs.remote_host }}
          ssh_user: ${{ github.event.inputs.ssh_user }}
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          deployment_dest: ${{ github.event.inputs.deployment_dest }}
          post_deploy_commands: ${{ github.event.inputs.post_deploy_commands }}
          cleanup_deleted_files: ${{ github.event.inputs.cleanup_deleted_files }}
          enable_health_check: ${{ github.event.inputs.enable_health_check }}
