name: Deploy Repository via rsync

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: "The SSH username"
        required: true
        default: '28985_deployer'
      remote_host:
        description: "The remote host (IP or domain)"
        required: true
        default: 'j0x.605.myftpupload.com'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy files
        uses: narethiya-godaddy/git-deploy-poc@v0.0.1
        with:
          ssh_user: ${{ github.event.inputs.ssh_user }}
          remote_host: ${{ github.event.inputs.remote_host }}
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          
