name: Deploy Repository via rsync

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: "The SSH username"
        required: true
        default: '28985_deployer'
      remote_host:
        description: "The remote host (IP or domain)"
        required: true
        default: 'j0x.605.myftpupload.com'
      deployment_dest:
        description: 'Path to a specific directory to deploy instead of the entire repository, leave blank for whole repository deployment.'
        required: false
        default: '.'
      post_deploy_commands:
        description: 'Commands to execute on the server after the deployment is complete.'
        required: false
        default: ''
      cleanup_deleted_files:
        description: 'Delete files from the server that have been removed from the repository.'
        required: false
        default: true
      enable_health_check:
        description: 'Check WordPress health after deployment and roll back if it fails. Disable to skip this step.'
        required: false
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy files
        uses: narethiya-godaddy/git-deploy-poc@v0.0.1
        with:
          remote_host: ${{ github.event.inputs.remote_host }}
          ssh_user: ${{ github.event.inputs.ssh_user }}
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          deployment_dest: ${{ github.event.inputs.deployment_dest }}
          post_deploy_commands: ${{ github.event.inputs.post_deploy_commands }}
          cleanup_deleted_files: ${{ github.event.inputs.cleanup_deleted_files }}
          enable_health_check: ${{ github.event.inputs.enable_health_check }}
